apiVersion: v1
kind: Service
metadata:
  name: dashboard-admin
  namespace: default
spec:
  ports:
  - port: 2587
    protocol: TCP
    targetPort: 2587
    nodePort: 32587
  selector:
    k8s-app: dashboard-admin
  sessionAffinity: None
  type: NodePort
